<div>
        <form action="" method="post">
            <label for="fname">Menu </label>
            <input type="text" name="menu" id="menu" ><br>
            <label for="lname">Categorie : </label>
            <input type="text" name="categorie" id="categorie"><br>
            <label for="id_user">Plats: </label>
            <label for="id_user">Prix du menu: </label>
            <input type="submit" name="Plats" id="Plats" value="Ajouter plats"><br>
        </form>
     
    </div>