<div>
        <form action="" method="post">
            <fieldset>
                <legend>Formulaire d'ajout de plats</legend>
                <label for="fname">Menu </label>
                <input type="text" name="menu" id="menu" ><br>

                <label for="lname">Nom du plat : </label>
                <input type="text" name="pname" id="pname"><br>

                <label for="id_user">Prix : </label>
                <input type="text" name="prix" id="prix"><br>

                <input type="submit" name="add" id="add" value="Ajouter"><br>
            </fieldset>

        </form>
    </div>